import mysql.connector as mcon
import time

def initialize():
    print("INITIALIZING..........")
    con = mcon.connect(host = "localhost", user = "root", passwd = "", charset = "utf8")
    time.sleep(1)
    if con.is_connected() == True:
        print("CONNECTION SUCCESSFULL")
    else:
        print("ERROR CONNECTING MYSQL")
    cur = con.cursor()
    cur.execute("DROP DATABASE IF EXISTS GROCERY_MANAGEMENT_SYS")
    cur.execute("CREATE DATABASE IF NOT EXISTS GROCERY_MANAGEMENT_SYS;")
    cur.execute("USE GROCERY_MANAGEMENT_SYS;")
    time.sleep(1)
    print("CREATED REQUIRED DATABASES")
    cur.execute("CREATE TABLE IF NOT EXISTS PROD_DETAILS (PROD_ID INT(3) AUTO_INCREMENT PRIMARY KEY, PROD_NAME VARCHAR(200) NOT NULL UNIQUE, PROD_SELL_COST INT(10) NOT NULL, PROD_QUANTITY INT NOT NULL);")
    cur.execute("CREATE TABLE IF NOT EXISTS MAN_DETAILS (MAN_ID INT(3) AUTO_INCREMENT PRIMARY KEY, MAN_NAME VARCHAR(200) NOT NULL, PROD_ID INT(3) NOT NULL, FOREIGN KEY(PROD_ID) REFERENCES PROD_DETAILS (PROD_ID) ON DELETE CASCADE ON UPDATE CASCADE);")
    cur.execute("CREATE TABLE IF NOT EXISTS CUST_DETAILS (CUST_ID INT(3) AUTO_INCREMENT PRIMARY KEY, CUST_NAME VARCHAR(30) NOT NULL, CUST_ADRS VARCHAR (200), CUST_MNO INT(10) NOT NULL);")
    cur.execute("CREATE TABLE IF NOT EXISTS PROD_BUY_COST (PROD_ID INT(3) NOT NULL, FOREIGN KEY(PROD_ID) REFERENCES PROD_DETAILS (PROD_ID) ON DELETE CASCADE ON UPDATE CASCADE, MAN_ID INT(3) NOT NULL, FOREIGN KEY(MAN_ID) REFERENCES MAN_DETAILS (MAN_ID) ON DELETE CASCADE ON UPDATE CASCADE, PROD_BUY_COST INT(20) NOT NULL);")
    time.sleep(1)
    print("CREATED REQUIRED TABLES")
    time.sleep(3)
    print("REQUIREMENTS INITIALIZED, YOU CAN START THE GROCERY STORE MANAGEMENT SOFTWARE")
    time.sleep(2)
    quit()


msg1 = "INITIALIZE GROCERY SHOP MANAGEMENT SYSTEM"
pmsg1 = msg1.center(120)
print(pmsg1)

print("WARNING : THIS PROCESS RESETS THE GROCERY SHOP MANAGEMENT SYSTEM IF ALREADY INSTALLED")
choice = input("DO YOU WANT TO INSTALL PRE-REQUISITES FOR GROCERY MANAGEMENT SYSTEM (Y/N):- ")
if choice == "Y":
    u = input("Enter User Name :")
    p = input("Enter User Password :")
    initialize()
elif choice == "N":
    print("OK, QUITING THE SYSTEM")
    time.sleep(2)
    quit()
else :
    print("CHOOSE THE CORRECT OPTIONS")
    quit()
